#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apache2'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'mysql', '1.3.0'
cookbook 'php'
cookbook 'ubuntu'
